### ISSUE TITLE
Mobile responsiveness & alignments are to be adjusted

### ISSUE THREAD

**Issue by SilverFoxA** [krupakumbhani/multiproduct-e-commerce#1]
While I feel the project structure can be organised a bit more, overall it looks good. Here's a few feedback which are to do with the mobile responsiveness.

![Screenshot 2023-02-13 at 11 29 59 AM](https://user-images.githubusercontent.com/6983070/218382743-803af58d-296d-40aa-b394-743f211dd267.png)
![Screenshot 2023-02-13 at 11 31 23 AM](https://user-images.githubusercontent.com/6983070/218382747-da3933c0-937a-46dc-b657-b29f4b9f904c.png)

**Comment by krupakumbhani** [comment]
Thank you for your feedback on the project structure. I appreciate your
insight on the mobile responsiveness aspect.
I'll make the updates and make sure to address the mobile responsiveness
issues. I'll update on GitHub once the changes have been made.

**Comment by krupakumbhani** [comment]
Hello Abhijit Das,

modified in terms of mobile responsiveness issue.

*GitHub Task Project Link:*
https://github.com/krupakumbhani/multiproduct-e-commerce

**Comment by SilverFoxA** [comment]
@mitulniqox Issue with responsiveness still persists. Please find the screenshots below. 

![Screenshot 2023-02-13 at 4 34 56 PM](https://user-images.githubusercontent.com/6983070/218442883-697aa16a-eb1f-424d-952f-b15a0870eabb.png)
![Screenshot 2023-02-13 at 4 34 31 PM](https://user-images.githubusercontent.com/6983070/218442853-cbbd741f-cac1-435f-a58d-7626f28be744.png)
![Screenshot 2023-02-13 at 4 34 42 PM](https://user-images.githubusercontent.com/6983070/218442865-759f7ef3-77eb-4549-9278-a2f31b184b90.png)
![Screenshot 2023-02-13 at 4 34 50 PM](https://user-images.githubusercontent.com/6983070/218442877-98551b77-dfa1-4537-979d-e531f17b0c9d.png)

**Comment by krupakumbhani** [comment]
Issue with responsiveness done. verify and let me update @SilverFoxA  .
